### ISSUE TITLE
content_for not cleared out before rendering new pages

### ISSUE THREAD

**Issue by sandro** [petebrowne/massimo#1]
I'm essentially doing nested layouts (which is probably a bad idea in the first place) via content_for and yield_content. The problem is that template_scope is memoized, so the content_blocks instance variable (from sinatra_more) never gets cleared out. This means when the first content_for is encountered, it gets repeatedly rendered for every subsequent page, even when that page has no content_for block. Removing the memoization fixes the problem.

**Comment by petebrowne** [comment]
I pushed a new version (0.7.4) that should fix your problem. It makes a bit more sense for each view/page to gets its own template scope. I'm hoping performance won't be affected too much

**Comment by sandro** [comment]
Cool. Did you push it to Rubygems yet?

**Comment by petebrowne** [comment]
It's there now
